### ISSUE TITLE
Segmentation fault issue on step 4

### ISSUE THREAD

**Issue by philefstat** [wmp9/DiNo-Plan#6]
So I'm running into a problem on step 4 of the quick start guide ("Discretise your PDDL+ Model").

When I run:

`bin/dino heathrow/model/domain3.pddl heathrow/model/pfile01.pddl `

I get a segmentation fault and I'm not sure what is causing it as there is no output that would hint to what the problem is (even when running with the --debug flag).

Any suggestions?

Here is the full output

```
Run with the -l flag or read the license file for terms
and conditions of use.
Run this program with "-h" for the list of options.
Bugs, questions, and comments should be directed to
"wiktor.piotrowski@kcl.ac.uk".

DiNo/UPMurphi compiler last compiled date: Nov 29 2016
===========================================================================

===========================================================================
DiNo Release 1.1
Discretised Nonlinear Heuristic Planner for PDDL+ models with continous processes and events.

DiNo Release 1.1 :
Copyright (C) 2015: W. Piotrowski, M. Fox, D. Long, D. Magazzeni, F. Mercorio.
DiNo Release 1.1 is based on UPMurphi release 3.0.

Universal Planner Murphi Release 3.0 :
Copyright (C) 2007 - 2015: G. Della Penna, B. Intrigila, D. Magazzeni, F. Mercorio.
Universal Planner Murphi Release 3.0 is based on CMurphi release 5.4.

CMurphi Release 5.4 :
Copyright (C) 2001 - 2003 by E. Tronci, G. Della Penna, B. Intrigila, I. Melatti, M. Zilli.
CMurphi Release 5.4 is based on Murphi release 3.1.

Murphi Release 3.1 :
Copyright (C) 1992 - 1999 by the Board of Trustees of
Leland Stanford Junior University.

===========================================================================
PDDL domain: heathrow/model/domain3.pddl (found)
PDDL problem: heathrow/model/pfile01.pddl (found)
DiNo model: heathrow/model/domain3.m (not found)
C++ source: heathrow/model/domain3.cpp (not found)
Executable planner: heathrow/model/domain3_planner (not found)
Compiling PDDL to DiNo model, please wait...


 Start DiNo translation... 

 ----- CONFIG FILE ----- 
PDDL Domain File: heathrow/model/domain3.pddl
PDDL Problem File: heathrow/model/pfile01.pddl
The output model will be written on file: heathrow/model/domain3.m
The output external function file will be written on file: heathrow/model/domain3.h
 ----- DOMAIN SETTINGS ----- 
 Time discretisation: 0.1
 Real number: (Integer): 5 digits for the integer part
 Real number: (Fractional) 2 digits for the fractional part
Segmentation fault (core dumped)
Executed command line: "/home/phil/work/2/bin/pddl2upm" heathrow/model/domain3.pddl heathrow/model/pfile01.pddl 
```

**Comment by wmp9** [comment]
Hi, 

Would you mind letting us know which OS and which version of flex are you using? flex 2.6 is known to cause issues and it's the default version for Ubuntu 16.04. 
If that's not the case, could you provide us with the domain and problem files (if possible) so that we can replicate the issue and investigate?

Finally, please note that we will be closing this repo (most likely today) as DiNo has moved to https://github.com/KCL-Planning/DiNo (so please make sure your version of DiNo is up to date with that repo).

**Comment by philefstat** [comment]
I am on Ubuntu 14.04 using flex 2.5.35. Which OS / flex version should I use?

Here is the domain file:

https://gist.github.com/philefstat/03a8a355d198907585a7ecc9c0b2e328

and the problem file:

https://gist.github.com/philefstat/e3d412bcb58e5e8b43c0b8242328b90c

I've used val on those and it doesn't throw any warnings or errors (though there may still be errors - I'm not that experienced with PDDL).

Ok that was actually a question of mine (which repo to use). I will switch to the KCL-Planning repo.

Thanks for your help!

**Comment by wmp9** [comment]
The OS and flex version seems fine. 
I will investigate the issue now. 

Thanks

**Comment by wmp9** [comment]
Looking at the domain, one issue is that DiNo cannot handle subtyping (e.g. terminal node - location and location plane - object). So you might want to rewrite the domain accordingly. However, DiNo is suited for PDDL+ domains, therefore it will not fair well on propositional domains like yours. I'd suggest using a different planner specifically designed to handle propositional domains.

**Comment by philefstat** [comment]
Ah ok, thanks for the advice.

This is just the initial model though and I will be adding events and processes that is why I was looking to use DiNo. I will do that first before trying again. 

Thanks for the help!
